(function(){
  const D=window.Axyon.Data,N=window.Axyon.Numbers,$=id=>document.getElementById(id),roman=n=>['0','I','II','III','IV','V'][n]||n;
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const fmtItems=o=>Object.entries(o||{}).map(([k,v])=>`${D.items[k]?.icon||'❓'} ${N.format(v)} ${D.items[k]?.name||k}`).join(' · ')||'Yok';
  const techName=id=>D.research.find(x=>x.id===id)?.name||id||'Başlangıçta açık';
  const reqText=r=>{const a=[];if(r?.machineTotal)a.push(`${r.machineTotal} toplam makine`);if(r?.sectors)a.push(`${r.sectors} açık bölge`);if(r?.ships)a.push(`${r.ships} gemi`);if(r?.battlesWon)a.push(`${r.battlesWon} zafer`);return a.join(' · ')||'Ek altyapı şartı yok';};
  const sumRepeatSeconds=levels=>D.repeatableResearch.reduce((total,r)=>total+Array.from({length:levels},(_,i)=>r.durationSec*Math.pow(1.22,i)).reduce((a,b)=>a+b,0),0);
  function summary(){
    const links=D.machines.reduce((n,m)=>n+Object.keys(m.recipe.in).length+Object.keys(m.recipe.out).length,0);
    const mainSeconds=D.research.reduce((n,t)=>n+t.durationSec,0),repeat20=sumRepeatSeconds(20);
    $('codex-summary').innerHTML=[
      ['Teknoloji',D.research.length],['Makine',D.machines.length],['Ürün',Object.keys(D.items).length],['Santral',D.powerPlants.length],
      ['Uzay birimi',D.ships.length+D.defenses.length],['Tarif bağlantısı',links],['Ana araştırma',N.formatTime(mainSeconds)],['Sonsuz 20 seviye',N.formatTime(repeat20)]
    ].map(([a,b])=>`<div class="codex-stat"><span>${a}</span><b>${b}</b></div>`).join('');
  }
  function technology(){
    const eras=D.eraOrder.map(era=>`<article class="codex-era searchable" data-search="${era} ${D.eraLabels[era]}"><header>${D.eraLabels[era]}</header><div class="codex-era-list">${D.research.filter(t=>t.era===era).map(t=>`<div class="codex-card searchable" data-search="${esc([t.name,t.desc,...t.prereq.map(techName),fmtItems(t.cost),reqText(t.requirements)].join(' '))}"><h3>${t.icon} ${t.name}</h3><p>${t.desc}</p><div class="codex-tags"><span class="codex-tag">⏱ ${N.formatTime(t.durationSec)}</span><span class="codex-tag">🪙 ${N.format(t.coins)}</span><span class="codex-tag">🏢 ${D.machines.find(x=>x.id===t.lab)?.name||t.lab} Mk ${t.labLevel}</span></div><div class="codex-cost">${fmtItems(t.cost)}</div><div class="codex-line"><b>Önkoşul:</b> ${t.prereq.map(techName).join(' → ')||'Yok'}</div><div class="codex-line"><b>Altyapı:</b> ${reqText(t.requirements)}</div></div>`).join('')}</div></article>`).join('');
    const repeat=`<article class="codex-era codex-repeat-era searchable" data-search="sonsuz omega tekrar araştırma"><header>♾️ Sınırsız Omega Araştırmaları</header><div class="codex-era-list">${D.repeatableResearch.map(r=>{const ten=Array.from({length:10},(_,i)=>r.durationSec*Math.pow(1.22,i)).reduce((a,b)=>a+b,0);return `<div class="codex-card searchable" data-search="${esc([r.name,r.desc,fmtItems(r.base)].join(' '))}"><h3>${r.icon} ${r.name}</h3><p>${r.desc}</p><div class="codex-tags"><span class="codex-tag">İlk süre ${N.formatTime(r.durationSec)}</span><span class="codex-tag">Süre ×1.22/seviye</span><span class="codex-tag">Maliyet ×${r.growth}/seviye</span></div><div class="codex-cost">İlk maliyet: ${fmtItems(r.base)}</div><div class="codex-line"><b>İlk 10 seviye temel süre:</b> ${N.formatTime(ten)}</div></div>`;}).join('')}</div></article>`;
    $('codex-tech').innerHTML=eras+repeat;
  }
  function machines(){ $('codex-machines').innerHTML=D.machines.map(m=>{const input=fmtItems(m.recipe.in),output=fmtItems(m.recipe.out);return `<article class="codex-card searchable" data-search="${esc([m.name,input,output,techName(m.tech)].join(' '))}"><h3>${m.icon} ${m.name}</h3><div class="recipe-flow"><div class="recipe-box"><b>Girdi</b><br>${input==='Yok'?'Kaynak yatağı':input}</div><span class="recipe-arrow">→</span><div class="recipe-box"><b>Çıktı</b><br>${output}</div></div><div class="codex-tags"><span class="codex-tag">⚡ ${m.power} kW</span><span class="codex-tag">📐 ${m.footprint} m²</span><span class="codex-tag">⏱ ${m.baseRate}/sn</span></div><div class="codex-line"><b>Açan teknoloji:</b> ${techName(m.tech)}</div><div class="codex-line"><b>İlk kurulum:</b> ${N.format(m.buildCost)}🪙 · <b>Otomasyon:</b> ${N.format(m.managerCost)}🪙</div><table class="mk-table"><tr><th>Sınıf</th><th>Üretim</th><th>Güç</th></tr>${D.levelMultipliers.map((x,i)=>`<tr><td>Mk ${roman(i+1)}</td><td>×${x}</td><td>×${x}</td></tr>`).join('')}</table></article>`;}).join('');}
  function items(){ $('codex-items').innerHTML=Object.entries(D.items).map(([id,it])=>{const prod=D.machines.filter(m=>m.recipe.out[id]).map(m=>m.name),source=it.externalSource?[it.externalSource]:[],cons=D.machines.filter(m=>m.recipe.in[id]).map(m=>m.name),fuel=D.powerPlants.filter(p=>p.fuel?.item===id).map(p=>p.name);return `<article class="codex-card searchable" data-search="${esc([it.name,it.desc,...prod,...cons,...fuel].join(' '))}"><h3>${it.icon} ${it.name}</h3><p>${it.desc}</p><div class="codex-tags"><span class="codex-tag">Katman ${it.tier}</span><span class="codex-tag">Depo ${N.format(it.cap)}</span><span class="codex-tag">${it.research?'Satılmaz':`${it.sell}🪙`}</span></div><div class="codex-line"><b>Üreten/Kazanılan:</b> ${[...prod,...source].join(', ')||'Yok'}</div><div class="codex-line"><b>Kullanan:</b> ${[...cons,...fuel].join(', ')||'Yok'}</div></article>`;}).join('');}
  function power(){ $('codex-power').innerHTML=D.powerPlants.map(p=>`<article class="codex-card searchable" data-search="${esc([p.name,techName(p.tech),p.fuel?D.items[p.fuel.item].name:'yakıtsız'].join(' '))}"><h3>${p.icon} ${p.name}</h3><div class="codex-tags"><span class="codex-tag">⚡ ${p.output} kW</span><span class="codex-tag">📐 ${p.footprint} m²</span><span class="codex-tag">${p.fuel?`${D.items[p.fuel.item].icon} ${p.fuel.rate}/sn`:'Yakıtsız'}</span></div><div class="codex-line"><b>Açan teknoloji:</b> ${techName(p.tech)}</div><div class="codex-line"><b>Kurulum:</b> ${N.format(p.buildCost)}🪙</div><table class="mk-table"><tr><th>Sınıf</th><th>Güç çarpanı</th></tr>${D.plantMultipliers.map((x,i)=>`<tr><td>Mk ${roman(i+1)}</td><td>×${x}</td></tr>`).join('')}</table></article>`).join('');}
  function space(){
    const ships=D.ships.map(d=>`<article class="codex-card searchable" data-search="${esc([d.name,techName(d.tech),fmtItems(d.cost),'gemi filo kargo yakıt'].join(' '))}"><h3>${d.icon} ${d.name}</h3><div class="codex-tags"><span class="codex-tag">⚔ ${d.attack}</span><span class="codex-tag">🛡 ${d.hull}</span><span class="codex-tag">📦 ${d.cargo}</span><span class="codex-tag">🚀 ${d.speed}</span><span class="codex-tag">⛽ ${d.fuel}/LY</span><span class="codex-tag">⏱ ${N.formatTime(d.buildSec)}</span></div><div class="codex-cost">${fmtItems(d.cost)}</div><div class="codex-line"><b>Teknoloji:</b> ${techName(d.tech)}</div></article>`);
    const defs=D.defenses.map(d=>`<article class="codex-card searchable" data-search="${esc([d.name,techName(d.tech),fmtItems(d.cost),'savunma baskın tamir'].join(' '))}"><h3>${d.icon} ${d.name}</h3><div class="codex-tags"><span class="codex-tag">⚔ ${d.attack}</span><span class="codex-tag">🛡 ${d.hull}</span></div><div class="codex-cost">${fmtItems(d.cost)}</div><div class="codex-line"><b>Teknoloji:</b> ${techName(d.tech)}</div><div class="codex-line"><b>Hasar sonrası:</b> Kurtarılabilen birimler Gezegen Bakım Atölyesinde onarılır.</div></article>`);
    const facilities=(D.repairFacilities||[]).map(d=>`<article class="codex-card searchable" data-search="${esc([d.name,techName(d.tech),d.zone,'tamir bakım hurda'].join(' '))}"><h3>${d.icon} ${d.name}</h3><p>${d.zone==='planet'?'Gezegen yüzeyi ve savunma birimlerini':d.zone==='orbital'?'Uzay gemileri ile yörünge tesislerini':'Pazar, tarama ve haberleşme uydularını'} onarır.</p><div class="codex-tags"><span class="codex-tag">Bölge: ${d.zone}</span><span class="codex-tag">Mk I–${roman(d.maxLevel)}</span><span class="codex-tag">Temel ${d.baseSecPerPoint} sn/hasar</span></div><div class="codex-line"><b>Açan teknoloji:</b> ${techName(d.tech)}</div><div class="codex-line"><b>Yükseltme:</b> Her seviye tamir kuyruğunu hızlandırır; tamir kiti, yörünge parçası, makine ünitesi ve ileri seviyede nano jel ister.</div></article>`);
    const automation=`<article class="codex-card searchable" data-search="otomasyon seviye yapay zeka modüler nanofabrikasyon"><h3>🧠 Beş Aşamalı Otomasyon</h3><p>Her makine sınıfı bağımsız olarak Otomasyon I–V seviyesine yükseltilir. İleri seviyeler üretimi hızlandırır ve güç tüketimini düşürür.</p><div class="codex-tags"><span class="codex-tag">Azami V</span><span class="codex-tag">+%${Math.round(D.automation.rateBonusPerLevel*100)} üretim/seviye</span><span class="codex-tag">-%${Math.round(D.automation.powerSavingPerLevel*100)} güç/seviye</span></div><div class="codex-line"><b>Teknoloji zinciri:</b> Temel Otomasyon → Otonom Fabrikalar → Modüler Üretim → Nanofabrikasyon</div></article>`;
    $('codex-space').innerHTML=[...ships,...defs,...facilities,automation].join('');
  }
  function validate(){const problems=[],itemIds=new Set(Object.keys(D.items)),techIds=new Set(D.research.map(x=>x.id));D.machines.forEach(m=>{[...Object.keys(m.recipe.in),...Object.keys(m.recipe.out)].forEach(id=>{if(!itemIds.has(id))problems.push(`${m.name}: bulunmayan ürün referansı ${id}`)});if(m.tech&&!techIds.has(m.tech))problems.push(`${m.name}: bulunmayan teknoloji ${m.tech}`);if(!m.name||!m.icon)problems.push(`${m.id}: eksik makine kimliği`)});D.powerPlants.forEach(x=>{if(x.fuel&&!itemIds.has(x.fuel.item))problems.push(`${x.name}: bulunmayan yakıt ${x.fuel.item}`);if(x.tech&&!techIds.has(x.tech))problems.push(`${x.name}: bulunmayan teknoloji ${x.tech}`)});D.research.forEach(t=>{t.prereq.forEach(id=>{if(!techIds.has(id))problems.push(`${t.name}: bulunmayan önkoşul ${id}`)});Object.keys(t.cost).forEach(id=>{if(!itemIds.has(id))problems.push(`${t.name}: bulunmayan maliyet ürünü ${id}`)});if(!D.machines.some(m=>m.id===t.lab))problems.push(`${t.name}: bulunmayan laboratuvar ${t.lab}`);if(!t.desc)problems.push(`${t.name}: açıklama eksik`)});Object.entries(D.items).forEach(([id,it])=>{const produced=D.machines.some(m=>m.recipe.out[id]);if(!produced&&!it.research&&!it.externalSource)problems.push(`${it.name}: hiçbir makine veya oyun sistemi tarafından üretilmiyor`);if(!it.desc)problems.push(`${it.name}: açıklama eksik`)});const reachable=new Set();let changed=true;while(changed){changed=false;D.research.forEach(t=>{if(!reachable.has(t.id)&&t.prereq.every(x=>reachable.has(x))){reachable.add(t.id);changed=true;}})}D.research.filter(t=>!reachable.has(t.id)).forEach(t=>problems.push(`${t.name}: teknoloji ağında ulaşılamıyor`));$('codex-validation').innerHTML=problems.length?`<div class="validation-error"><b>⚠ ${problems.length} veri sorunu bulundu</b><div class="validation-list">${problems.map(x=>`<div class="validation-item">${esc(x)}</div>`).join('')}</div></div>`:`<div class="validation-ok"><b>✅ Veri ağı doğrulandı</b><p>${D.research.length} teknoloji, ${D.machines.length} makine ve ${Object.keys(D.items).length} ürün referansında kırık bağlantı bulunmadı.</p></div>`;return problems;}
  function filter(){const q=$('codex-search').value.trim().toLocaleLowerCase('tr-TR'),cat=$('codex-category').value,problemsOnly=$('codex-problems-only').checked;document.querySelectorAll('.codex-section[data-category]').forEach(s=>s.classList.toggle('codex-hidden',cat!=='all'&&s.dataset.category!==cat));document.querySelectorAll('.searchable').forEach(x=>{const hit=!q||(x.dataset.search||'').toLocaleLowerCase('tr-TR').includes(q);x.classList.toggle('codex-hidden',!hit||problemsOnly);});if(problemsOnly){document.querySelectorAll('.codex-section[data-category]').forEach(s=>s.classList.add('codex-hidden'));$('validation').classList.remove('codex-hidden');}}
  summary();technology();machines();items();power();space();validate();$('codex-search').addEventListener('input',filter);$('codex-category').addEventListener('change',filter);$('codex-problems-only').addEventListener('change',filter);$('print-codex').addEventListener('click',()=>print());$('theme-codex').addEventListener('click',()=>{const d=document.documentElement;d.dataset.theme=d.dataset.theme==='dark'?'light':'dark';});
})();
