/** Axyon.UI v4 — ekran üretimi ve salt görünüm yardımcıları. */
(function(global){
  const D=global.Axyon.Data,N=global.Axyon.Numbers;
  const el=id=>document.getElementById(id);
  const fmtCost=obj=>Object.entries(obj||{}).map(([k,v])=>`${D.items[k]?.icon||''}${N.format(v)}`).join(' ')||'—';
  const materialLabel=(obj,prefix='')=>`${prefix}${fmtCost(obj)}`;
  const roman=n=>['0','I','II','III','IV','V'][n]||n;
  const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const unlocksFor=t=>{const out=[];D.machines.filter(m=>m.tech===t.id).forEach(m=>out.push(`${m.icon} <b>${escapeHtml(m.name)}</b>: ${Object.entries(m.recipe.in).map(([k,v])=>`${D.items[k]?.icon||''}${v}`).join(' ')||'Kaynak çıkarır'} → ${Object.entries(m.recipe.out).map(([k,v])=>`${D.items[k]?.icon||''}${v}`).join(' ')}`));D.powerPlants.filter(p=>p.tech===t.id).forEach(p=>out.push(`${p.icon} <b>${escapeHtml(p.name)}</b>: ${p.fuel?D.items[p.fuel.item].name+' yakıtlı': 'yakıtsız'} güç üretimi`));D.ships.filter(x=>x.tech===t.id).forEach(x=>out.push(`${x.icon} <b>${escapeHtml(x.name)}</b>: filo birimi, saldırı ${x.attack}, gövde ${x.hull}`));D.defenses.filter(x=>x.tech===t.id).forEach(x=>out.push(`${x.icon} <b>${escapeHtml(x.name)}</b>: gezegen savunması`));if(t.id==='marketSatellite')out.push('🛰️ <b>Pazar Uyduları</b>: tüm satışları yörüngeden yapar, filo kapasitesi tüketir');if(t.id==='scanner')out.push('📡 <b>Casus Sondaları</b>: hedef savunma, ganimet ve risk bilgisi toplar');if(t.id==='frontierDoctrine')out.push('🌌 <b>Sonsuz Cephe</b>: OGame tarzı sürekli büyüyen düşman hatları');return out.length?`<div class="res-unlocks"><span>Açılacaklar</span>${out.map(x=>`<small>${x}</small>`).join('')}</div>`:'';};

  function buildMachineCards(){}
  function buildPlantCards(state,E){
    const root=el('plants-container');if(!root)return;
    root.innerHTML=D.powerPlants.map(d=>{
      const p=state.plants[d.id],lv=E.plantLevel(state,d.id),locked=!E.isPlantUnlocked(state,d.id),req=E.plantBuildRequirements?E.plantBuildRequirements(state,d.id):{},up=lv<5?E.upgradeCost(d,lv,'plant'):null;
      const techName=D.research.find(x=>x.id===d.tech)?.name||d.tech||'Başlangıç';
      return `<article class="plant-card ${locked?'locked':''}" id="plant-${d.id}" data-help="plant:${d.id}"><div class="card-top"><span class="card-icon">${d.icon}</span><div><h3>${d.name} <small>Mk ${roman(lv)}</small></h3><p>${d.fuel?`${D.items[d.fuel.item].icon} yakıtlı`:'yakıtsız'} · +${N.format(E.plantOutput(state,d.id))} kW</p></div><b>×${p.count}</b></div>${locked?`<div class="locked-note">🔒 ${techName}</div>`:`<div class="card-actions"><button data-buildplant="${d.id}" class="btn-setting" ${E.canBuildPlant(state,d.id)?'':'disabled'}>Kur · ${fmtCost(req)}</button><button data-upgradeplant="${d.id}" class="btn-setting" ${E.canUpgradeClass(state,d.id,'plant')?'':'disabled'}>${lv>=5?'Mk V tamam':`Mk ${roman(lv+1)} · ${N.format(up.coins)}🪙 ${fmtCost(up.items)}`}</button></div>`}</article>`;
    }).join('');
  }

  function buildInventory(state,E){
    const root=el('inventory-list');if(!root)return;
    root.innerHTML=`<div class="inv-head"><span></span><span>Ürün</span><span>Stok / Akış</span><span>Uydu</span><span>Depo</span></div>`+Object.entries(D.items).map(([id,it])=>{
      const sellable=!it.research&&it.marketPolicy!=='forbidden'&&it.sell>0,cap=E.storageCap(state,id),pct=state.autoSellKeep[id]??0;
      return `<article class="inv-row ${it.research?'research-item':''}" id="inv-${id}" data-help="item:${id}">
        <label class="inv-check"><input type="checkbox" id="check-${id}" data-check="${id}" ${sellable?'':'disabled'} aria-label="${it.name} seç"></label>
        <button class="inv-info" data-info="${id}" data-help="item:${id}"><span class="inv-icon">${it.icon}</span><span class="inv-product"><b>${it.name}</b><small>${it.research?'Araştırma verisi':`${it.sell}🪙 liste fiyatı`}</small></span></button>
        <div class="inv-amount"><b id="amt-${id}">0</b><small>/<span id="cap-${id}">${N.format(cap)}</span></small><em id="flow-${id}"></em></div>
        ${sellable?`<button class="auto-toggle ${state.autoSell[id]?'on':''}" data-auto="${id}" data-help="ui:marketAuto">${state.autoSell[id]?'AÇIK ✓':'KAPALI'}</button>`:'<span class="no-sell compact">Satılmaz</span>'}
        <button class="storage-up" data-stor="${id}" data-help="ui:storageUpgrade" aria-label="${it.name} deposunu geliştir">⤢</button>
        <div class="inv-controls ${sellable?'':'disabled-controls'}">
          ${sellable?`<div class="inv-control-group"><span>Elde tut</span><div class="keep-set" data-help="ui:keepRatio">${[0,25,50,75,100].map(v=>`<button data-keep="${id}" data-pct="${v}" class="${pct===v?'active':''}">%${v}</button>`).join('')}</div></div><div class="inv-control-group market-only"><span>Satış yolu</span><small>Yalnızca Pazar Uydusu</small></div>`:`<small>Bu ürün araştırma, enerji veya bakım amacıyla korunur; satışa kapalıdır.</small>`}
        </div>
      </article>`;
    }).join('');
  }

  function buildResearch(state,E){
    const root=el('research-list');
    if(root)root.innerHTML=D.eraOrder.map((era,eraIndex)=>{
      const techs=D.research.filter(t=>t.era===era),done=techs.filter(t=>state.researched[t.id]).length;
      return `<details class="research-era" data-era="${era}" ${eraIndex<2?'open':''}><summary><span class="era-dot">${{alpha:'🔴',beta:'🟢',gamma:'🔵',delta:'🟣',omega:'⚪'}[era]}</span><div><h3>${D.eraLabels[era]}</h3><small>${done}/${techs.length} tamamlandı</small></div><span class="era-progress"><i style="width:${techs.length?done/techs.length*100:0}%"></i></span><b>⌄</b></summary><div class="research-era-list">${techs.map(t=>{
        const lab=D.machines.find(x=>x.id===t.lab);
        return `<article class="res-card" id="res-${t.id}" data-help="research:${t.id}"><div class="res-icon">${t.icon}</div><div class="res-body"><div class="res-title"><h3>${t.name}</h3><span class="era-badge">${era.toUpperCase()}</span></div><p>${t.desc}</p><div class="res-meta"><span>⏱ ${N.formatTime(t.durationSec)}</span><span>🏢 ${lab?.name||'Lab'} Mk ${t.labLevel}</span><span>${Number(t.coins||0)>0?'🪙 '+N.format(t.coins):'🧱 Kaynak tabanlı'}</span></div><div class="res-cost">${fmtCost(t.cost)}</div><div class="res-prereq">${t.prereq.length?`Önce: ${t.prereq.map(id=>D.research.find(x=>x.id===id)?.name||id).join(' · ')}`:'Başlangıç araştırması'}</div>${unlocksFor(t)}<div class="res-missing" id="res-missing-${t.id}"></div></div><button class="res-btn" data-research="${t.id}">Başlat</button></article>`;
      }).join('')}</div></details>`;
    }).join('');
    const rr=el('repeat-research-list');if(rr)rr.innerHTML=D.repeatableResearch.map(t=>`<article class="res-card repeat" id="repeat-${t.id}" data-help="repeat:${t.id}"><div class="res-icon">${t.icon}</div><div class="res-body"><div class="res-title"><h3>${t.name}</h3><span>Sv. <b id="repeat-level-${t.id}">0</b></span></div><p>${t.desc}</p><div class="res-meta"><span id="repeat-time-${t.id}"></span><span>🏢 Omega İstasyonu</span></div><div class="res-cost" id="repeat-cost-${t.id}"></div><div class="res-missing" id="repeat-missing-${t.id}"></div></div><button class="res-btn" data-repeat="${t.id}">Geliştir</button></article>`).join('');
  }

  function selectedItems(){return [...document.querySelectorAll('[data-check]:checked')].map(x=>x.dataset.check);}

  function render(state,E){
    const creditOpen=E.creditsVisible?E.creditsVisible(state):true;el('coin-display').textContent=creditOpen?N.format(state.coins):'Kilitli';el('total-earned').textContent=creditOpen?N.format(state.totalEarned):'İlk yörünge';el('multiplier-display').textContent='x'+E.globalMult(state).toFixed(2);el('threat-display').textContent=Math.round(state.galaxy.threat||0);const cap=E.capacityStatus?E.capacityStatus(state):null;el('fleet-display').textContent=cap?`${N.format(cap.fleet.used)}/${N.format(cap.fleet.max)}`:N.format(D.ships.reduce((n,d)=>n+(state.galaxy.ships[d.id]||0),0));
    const score=E.computeScore(state);el('score-display').textContent=N.format(score);el('topscore-display').textContent=N.format(state.topScore||score);
    const p=state._power||{supply:0,demand:0,ratio:1};el('power-supply').textContent=N.format(p.supply);el('power-demand').textContent=N.format(p.demand);el('power-bar').style.width=`${Math.min(100,p.demand?100*p.supply/p.demand:100)}%`;const ps=el('power-status');ps.textContent=p.ratio>=.99?'yeterli':p.ratio>0?'kısıtlı':'çöktü';ps.className='stat-status '+(p.ratio>=.99?'ok':p.ratio>.25?'warn':'bad');
    const opened=E.openSectorList(state).length,total=E.sectorsPerSide()**2,scan=state.firstOrbit?.sectorScans?.[0];el('land-used').textContent=opened;el('land-total').textContent=total;el('land-bar').style.width=`${opened/total*100}%`;el('land-expand-cost').textContent=scan?`Tarama ${N.formatTime(Math.max(0,(scan.finishAt-Date.now())/1000))}`:fmtCost(E.sectorOpenRequirements?E.sectorOpenRequirements(state):{});el('land-expand-btn').disabled=!E.canOpenSector(state);
    Object.keys(D.items).forEach(id=>{const a=el(`amt-${id}`);if(!a)return;a.textContent=N.format(state.inventory[id]||0);el(`cap-${id}`).textContent=N.format(E.storageCap(state,id));const f=state.flow[id]||0,sign=N.cmp?N.cmp(f,0):Number(f),abs=N.abs?N.abs(f):Math.abs(Number(f)||0),fe=el(`flow-${id}`),tiny=N.lt?N.lt(abs,.01):Number(abs)<.01;fe.textContent=tiny?'':`${sign>0?'▲':'▼'}${N.format(abs)}/sn`;fe.className=sign>=0?'flow-up':'flow-down';const row=el(`inv-${id}`);row?.querySelector('[data-auto]')?.classList.toggle('on',!!state.autoSell[id]);if(row?.querySelector('[data-auto]'))row.querySelector('[data-auto]').textContent=state.autoSell[id]?'AÇIK ✓':'KAPALI';row?.querySelectorAll('[data-keep]').forEach(b=>b.classList.toggle('active',Number(b.dataset.pct)===(state.autoSellKeep[id]||0)));});
    const sel=selectedItems();el('bulk-count').textContent=`${sel.length} seçili`;
    renderMarket(state,E);renderLiveTicker(state,E);renderResearchState(state,E);renderQuest(state);
    if(el('panel-power')?.classList.contains('active'))buildPlantCards(state,E);if(el('panel-report')?.classList.contains('active'))renderReport(state,E);if(el('panel-galaxy')?.classList.contains('active'))renderGalaxy(state,E);if(el('panel-combat')?.classList.contains('active'))global.Axyon.CombatUI?.render(state,E);
  }

  function renderMarket(state,E){
    const mk=Number((state.market.networkMk??state.market.level) || 0),dynamic=!!state.researched.marketNetworkMk1,prototype=!!state.market.prototypeBuilt;
    el('market-level').textContent=mk===0?'Mk 0':`Mk ${roman(mk)}`;if(el('market-satellites'))el('market-satellites').textContent=`${E.marketSatelliteCount(state)}/${E.marketSatelliteLimit(state)}`;el('market-capacity').textContent=N.format(E.marketCapacity(state));el('market-cooldown').textContent=N.formatTime(E.marketCooldownSec(state));el('market-last').textContent=N.format(state.market.lastRevenue||0);
    const master=el('market-master');master.disabled=!dynamic;master.textContent=!dynamic?(prototype?'🔒 PAZAR MK I':'🔒 MK 0 UYDU'):state.market.enabled?'AUTO AÇIK':'AUTO KAPALI';master.classList.toggle('active',dynamic&&state.market.enabled);
    const next=state.market.nextDispatchAt?Math.max(0,(state.market.nextDispatchAt-Date.now())/1000):0;el('market-next').textContent=!dynamic?(prototype?'Sözleşmeler':'Uydu gerekli'):state.market.enabled?N.formatTime(next):'Durduruldu';document.querySelectorAll('[data-globalkeep]').forEach(b=>b.classList.toggle('active',Number(b.dataset.globalkeep)===(state.market.keepPct||0)));
    const status=el('first-orbit-status');if(status){const route=state.firstOrbit?.route==='synthetic'?'Sentetik yakıt':'Petrol rotası',protoQueue=state.galaxy.satelliteQueue?.find(q=>q.satelliteId==='prototypeMarketSatellite');status.innerHTML=`<div><b>🚀 İlk Yörünge</b><small>${route}</small></div><span class="${prototype?'ok':''}">${prototype?'✓ Mk 0 yörüngede':protoQueue?`Fırlatma ${N.formatTime(Math.max(0,(protoQueue.finishAt-Date.now())/1000))}`:state.researched.prototypeOrbitalTrade?'Mk 0 üretime hazır':'Prototip Yörünge Ticareti gerekli'}</span>`;}
    const contracts=el('founding-contracts');if(contracts)contracts.innerHTML=D.firstOrbit.foundingContracts.map(c=>{const done=state.market.foundingContractsCompleted.includes(c.id),mission=state.market.contractMissions.find(m=>m.contractId===c.id),can=E.canStartFoundingContract(state,c.id);return `<article class="founding-contract ${done?'done':''}"><div><b>${done?'✓':'📦'} ${c.name}</b><small>${fmtCost(c.requires)} → ${N.format(c.creditReward)}🪙</small></div>${done?'<span>Tamamlandı</span>':mission?`<span>${N.formatTime(Math.max(0,(mission.finishAt-Date.now())/1000))}</span>`:`<button data-contract="${c.id}" ${can?'':'disabled'}>Gönder</button>`}</article>`;}).join('');
    const up=el('market-upgrade');if(!prototype){up.disabled=!E.canBuildSatellite(state,'prototypeMarketSatellite',1);up.dataset.action='prototype';up.textContent=state.researched.prototypeOrbitalTrade?`Mk 0 üret · ${fmtCost(E.satelliteDef('prototypeMarketSatellite').cost)}`:'Önce Prototip Yörünge Ticareti';}else if(!dynamic){up.disabled=true;up.dataset.action='research';up.textContent='Üç sözleşme + Pazar Ağı Mk I araştırması';}else if(E.marketSatelliteCount(state)<E.marketSatelliteLimit(state)){up.disabled=!E.canBuildSatellite(state,'marketSatellite',1);up.dataset.action='satellite';up.textContent=`Pazar Uydusu üret · ${E.marketSatelliteCount(state)}/${E.marketSatelliteLimit(state)}`;}else if(mk>=D.market.maxLevel){up.disabled=true;up.dataset.action='done';up.textContent='Pazar Ağı Mk III tamam';}else{const c=E.marketUpgradeCost(state);up.disabled=!E.canUpgradeMarket(state);up.dataset.action='upgrade';up.textContent=`Pazar Ağı Mk ${roman(mk+1)} · ${N.format(c.coins)}🪙 ${fmtCost(c.items)}`;}
  }

  function renderResearchState(state,E){
    const info=E.researchProgressInfo(state),activeBox=el('research-active');
    if(activeBox){
      if(info){const def=info.kind==='main'?D.research.find(x=>x.id===info.id):D.repeatableResearch.find(x=>x.id===info.id);activeBox.classList.remove('empty');activeBox.innerHTML=`<div class="active-research-main"><span class="active-research-icon">${def?.icon||'🔬'}</span><div><small>AKTİF ARAŞTIRMA</small><b>${def?.name||info.id}</b><div class="research-progress"><i style="width:${Math.round(info.progress*100)}%"></i></div><span>%${Math.round(info.progress*100)} · ${N.formatTime(info.leftSec)} kaldı</span></div><button id="cancel-research" class="btn-danger compact">İptal · %70 iade</button></div><div class="research-queue"><b>Kuyruk ${state.researchProgress.queue.length}/${E.researchQueueCapacity(state)-1}</b>${state.researchProgress.queue.map(q=>{const d=q.kind==='main'?D.research.find(x=>x.id===q.id):D.repeatableResearch.find(x=>x.id===q.id);return `<span>${d?.icon||'🔬'} ${d?.name||q.id}</span>`;}).join('')||'<span>Bekleyen araştırma yok</span>'}</div>`;
      }else{activeBox.classList.add('empty');activeBox.innerHTML='<span>🔬</span><div><b>Laboratuvarlar hazır</b><small>Bir teknoloji seçerek uzun dönem araştırmayı başlat.</small></div>';}
    }
    D.research.forEach(t=>{const node=el(`res-${t.id}`);if(!node)return;const done=!!state.researched[t.id],scheduled=state.researchProgress.active?.id===t.id||state.researchProgress.queue.some(q=>q.id===t.id),visible=E.isResearchVisible(state,t.id);node.classList.toggle('done',done);node.classList.toggle('scheduled',scheduled);node.classList.toggle('hidden-res',!visible&&!done);const b=node.querySelector('[data-research]'),missing=E.researchMissing(state,t.id);b.textContent=done?'✓ Tamamlandı':scheduled?'⏳ Sırada':state.researchProgress.active?'Kuyruğa Al':'Başlat';b.disabled=done||scheduled||!E.canResearch(state,t.id);const m=el(`res-missing-${t.id}`);if(m)m.textContent=done?'Kalıcı olarak açıldı.':missing.slice(0,3).join(' · ');});
    D.repeatableResearch.forEach(t=>{const node=el(`repeat-${t.id}`),cost=E.repeatCost(state,t.id),missing=E.repeatMissing(state,t.id);el(`repeat-level-${t.id}`).textContent=state.repeatResearch[t.id]||0;el(`repeat-cost-${t.id}`).textContent=fmtCost(cost);el(`repeat-time-${t.id}`).textContent=`⏱ ${N.formatTime(E.repeatDuration(state,t.id))}`;el(`repeat-missing-${t.id}`).textContent=missing.slice(0,3).join(' · ');node.classList.toggle('hidden-res',!state.researched.omegaScience);node.querySelector('[data-repeat]').disabled=!E.canRepeatResearch(state,t.id);});
  }

  function renderQuest(state){const Q=global.Axyon.Quests,p=Q.questProgress(state);if(!p){el('quest-desc').textContent='Ana görevler tamam — imparatorluk büyümeye devam ediyor';el('quest-bar').style.width='100%';el('quest-progress-text').textContent='∞';return;}el('quest-desc').textContent=p.quest.desc;el('quest-bar').style.width=`${Math.min(100,p.current/p.target*100)}%`;el('quest-progress-text').textContent=`${N.format(Math.min(p.current,p.target))} / ${N.format(p.target)}`;}

  function renderReport(state,E){
    const built=D.machines.filter(d=>state.machines[d.id].count>0),root=el('report-list');
    el('report-summary').innerHTML=`<div class="rs-box"><span>Hat türü</span><b>${built.length}</b></div><div class="rs-box"><span>Toplam makine</span><b>${E.machineCountTotal(state)}</b></div><div class="rs-box"><span>Yükseltme</span><b>${state.stats.buildingUpgrades||0}</b></div><div class="rs-box ${(state.galaxy.threat||0)>5?'bad':''}"><span>Tehdit</span><b>${(state.galaxy.threat||0).toFixed(1)}</b></div>`;
    if(!built.length){root.innerHTML='<div class="report-empty">Henüz üretim hattı yok.</div>';return;}
    root.innerHTML=built.sort((a,b)=>a.tier-b.tier).map(d=>{const m=state.machines[d.id],lv=E.machineLevel(state,d.id),rate=E.machineRate(state,d.id),eff=m.hasManager?m.eff:0,status=!m.hasManager?'Manuel':eff>=.95?'Tam hız':eff>0?`Kısıtlı %${Math.round(eff*100)}`:'Durdu',cls=!m.hasManager?'manual':eff>=.95?'ok':eff>0?'warn':'bad',out=Object.keys(d.recipe.out)[0];return `<div class="report-row" data-help="machine:${d.id}"><span class="rr-icon">${d.icon}</span><div class="rr-main"><div class="rr-name">${d.name} <span class="rr-count">Mk ${roman(lv)} · ×${m.count}</span></div><div class="rr-sub">${D.items[out].icon} ${N.format(m.hasManager?rate*eff:0)}/sn · ${N.format(E.machinePowerDemand(state,d.id))}kW</div></div><span class="rr-status ${cls}">${status}</span></div>`;}).join('');
  }

  function buildPalette(state,E){
    const m=el('fx-palette-machines'),p=el('fx-palette-plants');m.innerHTML='';p.innerHTML='';
    D.machines.forEach(d=>{if(!E.isMachineUnlocked(state,d.id))return;const lv=E.machineLevel(state,d.id),b=document.createElement('button');b.className='fx-palette-item';b.dataset.place=d.id;b.dataset.ptype='machine';b.dataset.help='machine:'+d.id;b.innerHTML=`<span class="pi-icon">${d.icon}</span><span class="pi-body"><span class="pi-name">${d.name} · Mk ${roman(lv)}</span><span class="pi-cost">${fmtCost(E.buildRequirements?E.buildRequirements(state,d.id):{})} · ${d.footprint}m² · ${N.format(E.machinePowerDemand({...state,machines:{...state.machines,[d.id]:{...state.machines[d.id],count:1,hasManager:true}}},d.id))}kW</span></span>`;m.appendChild(b);});
    D.powerPlants.forEach(d=>{if(!E.isPlantUnlocked(state,d.id))return;const b=document.createElement('button');b.className='fx-palette-item';b.dataset.place=d.id;b.dataset.ptype='plant';b.dataset.help='plant:'+d.id;b.innerHTML=`<span class="pi-icon">${d.icon}</span><span class="pi-body"><span class="pi-name">${d.name} · Mk ${roman(E.plantLevel(state,d.id))}</span><span class="pi-cost">${fmtCost(E.plantBuildRequirements?E.plantBuildRequirements(state,d.id):{})} · +${N.format(d.output)}kW</span></span>`;p.appendChild(b);});
  }

  function showInspector(state,E,entity){
    const box=el('fx-inspector');if(!entity){box.classList.add('hidden');return;}const d=entity.type==='plant'?E.pDef(entity.defId):E.mDef(entity.defId),lv=entity.type==='plant'?E.plantLevel(state,entity.defId):E.machineLevel(state,entity.defId),up=lv<5?E.upgradeCost(d,lv,entity.type):null;
    if(entity.type==='machine'){
      const m=state.machines[entity.defId],recipe=Object.entries(d.recipe.in).map(([k,v])=>`${D.items[k].icon}${v!==1?'×'+v:''}`).join(' ')||'Kaynak yatağı',out=Object.entries(d.recipe.out).map(([k,v])=>`${D.items[k].icon}${v!==1?'×'+v:''}`).join(' ');
      box.innerHTML=`<div class="fxi-head" data-help="machine:${d.id}"><span class="fxi-icon">${d.icon}</span><div><div class="fxi-name">${d.name} · Mk ${roman(lv)}</div><div class="fxi-sub">${recipe} → ${out}</div></div><button class="x" id="fxi-close">✕</button></div><div class="fxi-stats"><span>Sınıf adedi <b>${m.count}</b></span><span>Üretim <b>${N.format(E.machineRate(state,d.id))}/sn</b></span></div><div class="fxi-actions"><button class="fxi-btn" data-fxi="run">▶ Çalıştır</button>${(()=>{const al=E.automationLevel(state,d.id),ac=E.automationUpgradeCost(state,d.id);return `<button class="fxi-btn ${al>=5?'owned':''}" data-fxi="automation" ${al>=5||!E.canUpgradeAutomation(state,d.id)?'disabled':''}>${al>=5?'✓ Otomasyon Sv. 5':`🧠 Otomasyon ${al?'Sv. '+al+' → '+(al+1):'Kur'} · ${N.format(ac?.coins||0)}🪙`}</button>`;})()}<button class="fxi-btn" data-fxi="upgrade" ${E.canUpgradeClass(state,d.id,'machine')?'':'disabled'}>${lv>=5?'Mk V tamam':`⬆ Mk ${roman(lv+1)} · ${N.format(up.coins)}🪙 ${fmtCost(up.items)}`}</button><button class="fxi-btn" data-fxi="info">ⓘ Bilgi</button></div>`;
    }else box.innerHTML=`<div class="fxi-head" data-help="plant:${d.id}"><span class="fxi-icon">${d.icon}</span><div><div class="fxi-name">${d.name} · Mk ${roman(lv)}</div><div class="fxi-sub">+${N.format(E.plantOutput(state,d.id))} kW</div></div><button class="x" id="fxi-close">✕</button></div><div class="fxi-actions"><button class="fxi-btn" data-fxi="upgrade" ${E.canUpgradeClass(state,d.id,'plant')?'':'disabled'}>${lv>=5?'Mk V tamam':`⬆ Mk ${roman(lv+1)} · ${N.format(up.coins)}🪙 ${fmtCost(up.items)}`}</button></div>`;
    box.dataset.entity=entity.id;box.classList.remove('hidden');
  }

  function showNodeBuilder(state,E,nodeType,gx,gy){
    const box=el('fx-inspector'),node=D.resourceNodes[nodeType],matches=D.machines.filter(m=>E.extractorNodeType(m.id)===nodeType);if(!box||!node)return;
    box.innerHTML=`<div class="fxi-head" data-help="node:${nodeType}"><span class="fxi-icon">${node.icon}</span><div><div class="fxi-name">${node.name}</div><div class="fxi-sub">Hücre ${gx}, ${gy} · Bu kaynağa uygun çıkarıcı seç</div></div><button class="x" id="fxi-close">✕</button></div><div class="node-build-list">${matches.map(d=>{const unlocked=E.isMachineUnlocked(state,d.id),cost=E.buildRequirements?E.buildRequirements(state,d.id):{};return `<button class="node-build-option" data-build-node="${d.id}" ${!unlocked||!E.canBuild(state,d.id)?'disabled':''}><span>${d.icon}</span><div><b>${d.name}</b><small>${unlocked?`${fmtCost(cost)} · ${N.format(d.baseRate)} temel hız`:`🔒 ${D.research.find(t=>t.id===d.tech)?.name||'Teknoloji gerekli'}`}</small></div></button>`;}).join('')||'<small>Bu kaynak için çıkarıcı tanımlı değil.</small>'}</div><p class="fxi-note">İnşa düğmesine bastıktan sonra aynı yatağın üzerine dokunarak yerleştir.</p>`;
    box.dataset.nodeType=nodeType;box.dataset.nodeX=gx;box.dataset.nodeY=gy;delete box.dataset.entity;box.classList.remove('hidden');
  }

  function showItemInfo(state,E,id){const x=E.itemInfo(state,id);el('iteminfo-title').textContent=`${x.icon} ${x.name}`;el('iteminfo-body').innerHTML=`<p>${escapeHtml(x.desc)}</p><div class="info-grid"><span>Stok <b>${N.format(x.amount)} / ${N.format(x.cap)}</b></span><span>Liste değeri <b>${x.research?'Satılmaz':x.sell+'🪙'}</b></span><span>Üreten <b>${x.producers.join(', ')||'—'}</b></span><span>Kullanan <b>${[...x.consumers,...x.fuelFor].join(', ')||'—'}</b></span></div>`;showModal('iteminfo-modal');}

  function renderGalaxy(state,E){
    const now=Date.now(),raid=Math.max(0,(state.galaxy.nextRaidAt-now)/1000);el('raid-timer').textContent=N.formatTime(raid);const sc=E.scanCost(state);el('scan-cost').textContent=state.researched.scanner?`Maliyet: ${N.format(sc.coins)}🪙 + ${sc.processor} ${D.items.processor.icon}`:'Yıldız Tarayıcı araştırması gerekli';el('scan-system').disabled=!E.canScan(state);
    const targets=state.galaxy.targets.filter(t=>t.discovered);el('target-list').innerHTML=targets.length?targets.map(t=>`<article class="target-card ${t.defeated?'defeated':''}" data-help="target:${t.id}"><div><b>${t.defeated?'✅':'☠️'} ${t.name}</b><small>${t.type} · ${t.distance} LY · Güç ${N.format(t.strength)}${t.defeated&&!t.colonized&&t.recoveryAt?` · Toparlanma ${N.formatTime(Math.max(0,(t.recoveryAt-now)/1000))}`:''}</small></div>${t.colonized?'<span class="badge">Koloni</span>':t.defeated?(t.colonizable===false?'<span class="badge">Cephe temizlendi</span>':`<button data-colonize="${t.id}" class="btn-setting" ${E.canColonize(state,t.id)?'':'disabled'}>İstila / Kolonileştir</button>`):`<div class="target-actions"><button data-spy="${t.id}" class="btn-setting" ${E.canSpyTarget&&E.canSpyTarget(state,t.id)?'':'disabled'}>Casusluk</button><button data-attack="${t.id}" class="btn-setting" ${state.researched.fleetCommand?'':'disabled'}>Saldır</button></div>`}</article>`).join(''):'<div class="report-empty">Henüz sistem keşfedilmedi.</div>';
    el('shipyard-list').innerHTML=(D.satellites||[]).map(d=>{const locked=d.tech&&!state.researched[d.tech],count=state.galaxy.satellites?.[d.id]||0;return `<div class="ship-row ${locked?'locked':''}" data-help="satellite:${d.id}"><span class="ship-icon">${d.icon}</span><div><b>${d.name}</b><small>Yörüngede: ${count} · Limit ${E.marketSatelliteCount(state)}/${E.marketSatelliteLimit(state)}<br>${fmtCost(d.cost)}</small></div><input id="sat-count-${d.id}" type="number" min="1" max="9" value="1"><button data-buildsat="${d.id}" ${locked||!E.canBuildSatellite(state,d.id,1)?'disabled':''}>Üret</button></div>`;}).join('')+D.ships.map(d=>{const locked=d.tech&&!state.researched[d.tech];return `<div class="ship-row ${locked?'locked':''}" data-help="ship:${d.id}"><span class="ship-icon">${d.icon}</span><div><b>${d.name}</b><small>Hangar: ${state.galaxy.ships[d.id]||0} · Kapasite ${E.capacityStatus?E.capacityStatus(state).fleet.used+'/'+E.capacityStatus(state).fleet.max:'—'} · Saldırı ${d.attack} · Gövde ${d.hull}<br>${fmtCost(d.cost)}</small></div><input id="ship-count-${d.id}" type="number" min="1" max="99" value="1"><button data-buildship="${d.id}" ${locked||!E.canBuildShip(state,d.id,1)?'disabled':''}>Üret</button></div>`;}).join('');
    el('ship-queue').innerHTML=(state.galaxy.satelliteQueue?.length?state.galaxy.satelliteQueue.map(q=>`<div class="queue-row">${E.satelliteDef(q.satelliteId)?.icon||'🛰️'} ${q.count} ${E.satelliteDef(q.satelliteId)?.name||q.satelliteId}<b>${N.formatTime(Math.max(0,(q.finishAt-now)/1000))}</b></div>`).join(''):'')+(state.galaxy.shipQueue.length?state.galaxy.shipQueue.map(q=>`<div class="queue-row" data-help="ship:${q.shipId}">${E.shipDef(q.shipId).icon} ${q.count} ${E.shipDef(q.shipId).name}<b>${N.formatTime(Math.max(0,(q.finishAt-now)/1000))}</b></div>`).join(''):'<small>Üretim kuyruğu boş.</small>');
    const ds=E.defenseStats(state);el('defense-power').textContent=N.format(ds.attack+ds.hull*.35)+' güç';el('defense-list').innerHTML=D.defenses.map(d=>{const locked=d.tech&&!state.researched[d.tech];return `<div class="ship-row ${locked?'locked':''}" data-help="defense:${d.id}"><span class="ship-icon">${d.icon}</span><div><b>${d.name}</b><small>Kurulu: ${state.galaxy.defenses[d.id]||0} · Kapasite ${E.capacityStatus?E.capacityStatus(state).defense.used+'/'+E.capacityStatus(state).defense.max:'—'} · ${fmtCost(d.cost)}</small></div><input id="def-count-${d.id}" type="number" min="1" max="99" value="1"><button data-builddef="${d.id}" ${locked||!E.canBuildDefense(state,d.id,1)?'disabled':''}>Kur</button></div>`;}).join('');
    el('mission-list').innerHTML=state.galaxy.missions.length?state.galaxy.missions.map(m=>{const t=E.targetById(state,m.targetId),end=m.status==='outbound'?m.arrivalAt:m.returnAt;return `<div class="mission-row" data-help="target:${m.targetId}"><span>${m.status==='outbound'?'⚔️':'↩️'} ${t?.name||m.targetId}</span><b>${m.status==='outbound'?'Varış':'Dönüş'} ${N.formatTime(Math.max(0,(end-now)/1000))}</b></div>`;}).join(''):'<div class="report-empty">Aktif görev yok.</div>';
    const gr=el('galaxy-reports');if(gr)gr.innerHTML=state.galaxy.reports.slice(0,5).map(r=>`<article class="galaxy-report ${r.type}"><div><b>${escapeHtml(r.title)}</b><small>${new Date(r.time).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</small></div><p>${escapeHtml(r.body)}</p></article>`).join('')||'<div class="report-empty">Henüz rapor yok.</div>';
  }


  function renderLiveTicker(state,E){
    const root=el('ticker-list'),cnt=el('ticker-count'); if(!root)return; const now=Date.now(),rows=[];
    (state.galaxy.missions||[]).forEach(m=>{const t=E.targetById(state,m.targetId),end=m.status==='outbound'?m.arrivalAt:m.returnAt;rows.push({time:end,html:`<span>${m.status==='outbound'?'⚔️ Giden filo':'↩️ Dönen filo'} · ${escapeHtml(t?.name||m.targetId)}</span><b>${N.formatTime(Math.max(0,(end-now)/1000))}</b>`});});
    if(state.market?.enabled&&state.market.nextDispatchAt)rows.push({time:state.market.nextDispatchAt,html:`<span>🛰️ Pazar sevkiyatı</span><b>${N.formatTime(Math.max(0,(state.market.nextDispatchAt-now)/1000))}</b>`});
    if(state.galaxy.nextRaidAt)rows.push({time:state.galaxy.nextRaidAt,html:`<span>🚨 Uzaylı baskını</span><b>${N.formatTime(Math.max(0,(state.galaxy.nextRaidAt-now)/1000))}</b>`});
    (state.galaxy.shipQueue||[]).slice(0,3).forEach(q=>rows.push({time:q.finishAt,html:`<span>🚀 ${escapeHtml(E.shipDef(q.shipId).name)} üretimi ×${q.count}</span><b>${N.formatTime(Math.max(0,(q.finishAt-now)/1000))}</b>`}));
    (state.galaxy.reports||[]).slice(0,2).forEach(r=>rows.push({time:r.time,html:`<span>📡 ${escapeHtml(r.title)}</span><b>${new Date(r.time).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</b>`}));
    rows.sort((a,b)=>a.time-b.time); cnt.textContent=String(rows.length); root.innerHTML=rows.slice(0,5).map(r=>`<div class="ticker-row">${r.html}</div>`).join('')||'<div class="ticker-row muted">Aktif haber yok.</div>';
  }

  function renderFleetModal(state,E,target){el('fleet-title').textContent=`⚔️ ${target.name} — Güç ${N.format(target.strength)}`;el('fleet-body').innerHTML=`<p class="panel-hint">Gidiş-dönüş yakıtı sefer başında ayrılır. Sonuç varışta hesaplanır.</p><div class="fleet-select">${D.ships.map(d=>`<label><span>${d.icon} ${d.name} <small>mevcut ${state.galaxy.ships[d.id]||0}</small></span><input data-fleetship="${d.id}" type="number" min="0" max="${state.galaxy.ships[d.id]||0}" value="0"></label>`).join('')}</div><div id="fleet-preview" class="fleet-preview">Gemi seçilmedi.</div>`;el('fleet-modal').dataset.target=target.id;showModal('fleet-modal');}
  function fleetSelection(){const out={};document.querySelectorAll('[data-fleetship]').forEach(i=>out[i.dataset.fleetship]=Math.max(0,Math.floor(Number(i.value)||0)));return out;}

  function renderAchievements(state){el('ach-grid').innerHTML=D.achievements.map(a=>`<div class="ach-item ${state.achievements[a.id]?'done':''}"><span>${state.achievements[a.id]?'🏆':'🔒'}</span><span>${a.desc}</span></div>`).join('');}
  function setToolbarMode(mode){document.querySelectorAll('.fx-tool[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));const hints={select:'Yapıya tıkla: seç · sürükle: taşı · boşluk sürükle: kaydır',place:'Yerleştirmek için açık yüzeye tıkla',conveyor:'Kaynak yapı → hedef yapı',power:'Santral → makine',delete:'Yapı veya bağlantıya tıkla: sil'};el('fx-hint').textContent=hints[mode]||'';}
  function switchTab(tab){document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));el(`panel-${tab}`).classList.add('active');el(`tab-${tab}`).classList.add('active');}
  function pulse(){}function spawnFloat(text,x,y){const n=document.createElement('div');n.className='float-text';n.textContent=text;n.style.left=x+'px';n.style.top=y+'px';el('float-layer').appendChild(n);setTimeout(()=>n.remove(),900);}
  const showModal=id=>el(id).classList.remove('hidden'),hideModal=id=>el(id).classList.add('hidden');

  global.Axyon=global.Axyon||{};global.Axyon.UI={el,buildMachineCards,buildPlantCards,buildInventory,buildResearch,render,renderMarket,renderGalaxy,renderLiveTicker,renderFleetModal,fleetSelection,selectedItems,pulse,spawnFloat,showModal,hideModal,renderAchievements,switchTab,showItemInfo,renderReport,buildPalette,showInspector,showNodeBuilder,setToolbarMode};
})(window);
