const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),clear:()=>store.clear(),key:i=>[...store.keys()][i]??null,get length(){return store.size;}};
const ctx={console,Date,Math,localStorage,setTimeout,clearTimeout};ctx.globalThis=ctx;vm.createContext(ctx);
for(const f of ['data/feature-flags.js','vendor/break_eternity/break_eternity.min.js','src/core/economy-number.js','src/core/lossless-json.js','src/services/save-migrator-v16.js','data/canonical/game-data.v4.4.final.js','src/core/canonical-data-loader.js','src/core/numbers.js','data/config.js','src/core/economy.js','src/services/save-service.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
const {Economy:E,SaveService:S}=ctx.Axyon;const assert=(x,m)=>{if(!x)throw new Error(m)};
assert(S.bootstrap()===null,'first launch must wait for commander name');assert(S.listProfiles().length===0,'first launch created an unnamed profile');assert(S.load()===null,'load should be empty before commander creation');
const initial=S.createProfile('Ahmet');assert(initial.ok,'first commander creation failed');
let state=S.load();state.coins=987654;state.inventory.ironOre=444;state.topScore=12345;state.sectorsOpened=9;state.researched.basics=true;state.galaxy.ships.fighter=5;state.galaxy.reports.push({id:'test-report'});state.machines.ironMine.automationLevel=5;state.maintenance.integrity.planet=41;state.maintenance.damagedShips.fighter=3;state.maintenance.repairQueue.push({id:'repair-test'});state.repeatResearch.repairEfficiency=7;S.save(state);
const first=S.currentProfileId();const created=S.createProfile('Sevcan');assert(created.ok,'profile create failed');assert(S.currentProfileId()!==first,'new profile not selected');
const unsafe=S.createProfile('<img onerror=alert(1)> Ahmet');assert(unsafe.ok&&!/[<>'"&`]/.test(unsafe.profile.name),'profile name sanitization failed');assert(S.deleteProfile(unsafe.profile.id),'sanitized test profile delete failed');assert(S.selectProfile(created.profile.id),'return to second profile failed');
let second=S.load();assert(second.coins===180&&second.inventory.ironOre===0,'profiles leaked state');
assert(S.selectProfile(first),'profile switch failed');state=S.load();assert(state.coins===987654&&state.inventory.ironOre===444,'first profile state lost');
// Corrupt/imported values must be normalized instead of poisoning the simulation with NaN/Infinity.
const malformed=E.normalizeState({version:15,coins:'NaN',inventory:{ironOre:-50,copperOre:'Infinity'},machines:{ironMine:{count:'Infinity',automationLevel:99}},maintenance:{integrity:{planet:'bad',orbital:-25,satellite:999}},map:{openSectors:{'bad':true},nodes:{}},grid:{entities:{broken:{type:'machine',defId:'missing',x:'x',y:0}}}});
assert(Number.isFinite(malformed.coins)&&malformed.coins>=0,'malformed coins not sanitized');assert(malformed.inventory.ironOre===0&&malformed.inventory.copperOre===0,'malformed inventory not sanitized');assert(malformed.machines.ironMine.count===0&&malformed.machines.ironMine.automationLevel===5,'malformed machine state not sanitized');assert(malformed.maintenance.integrity.planet===100&&malformed.maintenance.integrity.orbital===0&&malformed.maintenance.integrity.satellite===100,'integrity sanitization failed');assert(E.openSectorList(malformed).length===1,'corrupt map did not recover starting sectors');assert(Object.keys(malformed.grid.entities).length===0,'invalid grid entities survived normalization');

const fresh=S.resetCurrent({theme:'light'});assert(fresh.coins===180,'coins not reset');assert(fresh.inventory.ironOre===0,'inventory not reset');assert(fresh.topScore===0,'score not reset');assert(fresh.sectorsOpened===0,'sector counter not reset');assert(!fresh.researched.basics,'research not reset');assert(fresh.repeatResearch.repairEfficiency===0,'repeat research not reset');assert(fresh.galaxy.ships.fighter===0,'fleet not reset');assert(fresh.galaxy.reports.length===0,'combat reports not reset');assert(fresh.machines.ironMine.automationLevel===0,'automation level not reset');assert(fresh.maintenance.integrity.planet===100,'planet damage not reset');assert(fresh.maintenance.damagedShips.fighter===0,'damaged fleet not reset');assert(fresh.maintenance.repairQueue.length===0,'repair queue not reset');assert(E.openSectorList(fresh).length===1,'starting regions not restored');assert(fresh.settings.theme==='light','theme preservation failed');
S.save(fresh);const reloaded=S.load();assert(reloaded.coins===180&&reloaded.topScore===0,'reset state was overwritten by autosave behavior');
assert(S.deleteProfile(first),'profile delete failed');assert(!S.listProfiles().some(p=>p.id===first),'deleted profile remains');
console.log('PASS profile-reset: isolated local profiles, switching, deletion, corrupt-import sanitization and full reset');
